<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dt_tokokitaHai</name>
   <tag></tag>
   <elementGuidId>a53d5acd-f8d6-40ef-a486-8a2cbba6e6bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>div[class='css-trlcwy'] div:nth-child(1) div:nth-child(1) dl:nth-child(1) dt:nth-child(1)</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>dt.chakra-stat__label.css-14go5ty</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>dt</value>
      <webElementGuid>32fcc683-cdbc-4dd5-b812-cbafdb80dd7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-stat__label css-14go5ty</value>
      <webElementGuid>490065e5-7837-4366-99ce-44f1a96d69cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>tokokita</value>
      <webElementGuid>a45985b8-0896-448e-aa60-3128c44c5c63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;css-k008qs&quot;]/div[@class=&quot;css-1r35f0l&quot;]/div[@class=&quot;chakra-container css-9rmdie&quot;]/div[@class=&quot;css-j7qwjs&quot;]/div[@class=&quot;css-trlcwy&quot;]/div[@class=&quot;css-13pc7q0&quot;]/div[@class=&quot;chakra-stat css-1mbo1ls&quot;]/dl[1]/dt[@class=&quot;chakra-stat__label css-14go5ty&quot;]</value>
      <webElementGuid>ea4f983d-e47f-4bf3-a11a-b4af7e078136</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div[2]/div/div/div/div/dl/dt</value>
      <webElementGuid>eefd586a-179e-42aa-8389-194b7f0a7bf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='logout'])[1]/following::dt[1]</value>
      <webElementGuid>068bf7ca-990d-4e2b-84a2-a9b946be55cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='tokokita'])[1]/following::dt[1]</value>
      <webElementGuid>fbed2f90-080b-47e4-9931-32c3cd3afb35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='hai'])[1]/preceding::dt[1]</value>
      <webElementGuid>92f8f0aa-2837-4add-9db5-17bf5b3e80c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='penjualan'])[2]/preceding::dt[1]</value>
      <webElementGuid>b6d89600-6b4c-4498-b9fc-212a90fa71b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//dt</value>
      <webElementGuid>ba86bacb-a303-47a1-8f91-9ef5571dd506</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//dt[(text() = 'tokokita' or . = 'tokokita')]</value>
      <webElementGuid>e9fa683d-53f6-4a13-ac41-52379afdc308</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
